---
app:
  timeFormat: "2006-01-02 15:04:05"
  jwtSecret: "blog"
  tokenTimeout: 3600 # 单位秒
server:
  runMode: "debug"
  host: "10.1.7.198"
  port: "8080"
  readTimeout: 60
  writeTimeout: 60
database:
  mode: "mysql"
  host: "10.1.7.198"
  port: "3306"
  user: "root"
  password: "123456"
  dbName: "blog"
  salt: "blog"
