version: "3.7"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    volumes:
      - /data/redis:/data
    networks:
      - blog
    restart: always
    container_name: blog_redis

  mysql:
    image: mysql:latest
    ports:
      - "3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./backend/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - blog
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    container_name: blog_db

  gin:
    build:
      context: ./backend
    ports:
      - "8000"
    volumes:
      - /data/gin/upload:/go/src/upload
    networks:
      - blog
    depends_on:
      - mysql
      - redis
    container_name: blog_gin

  nginx:
    build:
      context: ./fronted
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./fronted/nginx.conf:/etc/nginx/nginx.conf
      - ./fronted/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf
      - ./fronted/cert/poorops.com.key:/etc/nginx/poorops.com.key
      - ./fronted/cert/poorops.com.pem:/etc/nginx/poorops.com.pem
    networks:
      - blog
    depends_on:
      - gin
    container_name: blog_nginx

  elasticsearch:
    image: elasticsearch:7.4.2
    ports:
      - "9200"
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - blog
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    container_name: blog_elasticsearch

networks:
  blog:
